# waypost configuration
#
#   a big shoutout to WaLLy3K https://firebog.net/ for the aggregated lists
#


[server]
# address to bind
host = ""

# ports to bind
DNSPort = 53
MgmtPort = 5554

    [server.logging]
    # server log level
    # ERROR | WARN | INFO | DEBUG | TRACE
    level = "INFO"

    # server log location
    # *only stdout supported*
    #location = "stdout"


[resolve]
nameservers = [
    # docker dns
    "127.0.0.11",
    
    # google
    "8.8.8.8",
    "8.8.4.4",

    # cloudflare
    "1.1.1.1",
    "1.0.0.1",
]


[cache]
enabled = true
ttl = 7200 #seconds


[hosts]
# enable local host mapping
enabled = true

# remote host mappings to fetch
upstreams = []

    # list of host address pairs
    [hosts.list]
    "local.waypost" = "127.0.0.1"
    "localhost.waypost" = "127.0.0.1"


[filtering]
# enable filtering
enabled = true

    [filtering.blacklist]
    # enable blacklist filtering
    enabled = true

    # local list of domains to blacklist
    list = [
    ]

    # remote list of domains to blacklist
    upstreams = [
        ##
        ## Suspicious
        ##
        "https://hosts-file.net/grm.txt",
        "https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts",
        "https://raw.githubusercontent.com/StevenBlack/hosts/master/data/KADhosts/hosts",
        "https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Spam/hosts",
        "https://v.firebog.net/hosts/static/w3kbl.txt",
        "https://v.firebog.net/hosts/BillStearns.txt",
        "http://sysctl.org/cameleon/hosts",
        "https://www.dshield.org/feeds/suspiciousdomains_Low.txt",
        "https://www.dshield.org/feeds/suspiciousdomains_Medium.txt",
        "https://www.dshield.org/feeds/suspiciousdomains_High.txt",
        "https://www.joewein.net/dl/bl/dom-bl-base.txt",
        "https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt",
        "https://hostsfile.org/Downloads/hosts.txt",
        "https://someonewhocares.org/hosts/zero/hosts",
        "https://raw.githubusercontent.com/Dawsey21/Lists/master/main-blacklist.txt",
        "https://raw.githubusercontent.com/vokins/yhosts/master/hosts",
        "http://winhelp2002.mvps.org/hosts.txt",
        #"https://hostsfile.mine.nu/hosts0.txt",
        #"https://v.firebog.net/hosts/Kowabit.txt",
        #"https://adblock.mahakala.is",

        ##
        ## Advertisers
        ##
        "https://adaway.org/hosts.txt",
        "https://v.firebog.net/hosts/AdguardDNS.txt",
        "https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt",
        "https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt",
        "https://hosts-file.net/ad_servers.txt",
        "https://v.firebog.net/hosts/Easylist.txt",
        "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts;showintro=0",
        "https://raw.githubusercontent.com/StevenBlack/hosts/master/data/UncheckyAds/hosts",
        "https://www.squidblacklist.org/downloads/dg-ads.acl",

        ##
        ## Tracking and telemetry
        ##
        "https://v.firebog.net/hosts/Easyprivacy.txt",
        "https://v.firebog.net/hosts/Prigent-Ads.txt",
        "https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt",
        "https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts",
        "https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt",
        "https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt",
        "https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt",
        #"https://v.firebog.net/hosts/Airelle-trc.txt",

        # Malicious
        "https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt",
        "https://mirror1.malwaredomains.com/files/justdomains",
        "https://hosts-file.net/exp.txt",
        "https://hosts-file.net/emd.txt",
        "https://hosts-file.net/psh.txt",
        "https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt",
        "https://www.malwaredomainlist.com/hostslist/hosts.txt",
        "https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt",
        "https://v.firebog.net/hosts/Prigent-Malware.txt",
        "https://v.firebog.net/hosts/Prigent-Phishing.txt",
        "https://phishing.army/download/phishing_army_blocklist_extended.txt",
        "https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt",
        "https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt",
        "https://ransomwaretracker.abuse.ch/downloads/CW_C2_DOMBL.txt",
        "https://ransomwaretracker.abuse.ch/downloads/LY_C2_DOMBL.txt",
        "https://ransomwaretracker.abuse.ch/downloads/TC_C2_DOMBL.txt",
        "https://ransomwaretracker.abuse.ch/downloads/TL_C2_DOMBL.txt",
        "https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist",
        "https://v.firebog.net/hosts/Shalla-mal.txt",
        "https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Risk/hosts",
        "https://www.squidblacklist.org/downloads/dg-malicious.acl",
        "https://raw.githubusercontent.com/HorusTeknoloji/TR-PhishingList/master/url-lists.txt",
        #"https://v.firebog.net/hosts/Airelle-hrsk.txt",
    ]

    [filtering.whitelist]
    # enable whitelist filtering
    enabled = true

    # local list of domains to whitelist
    list = [
        # always allow localhost
        "localhost",
        "127.0.0.1",

        # google services
        "www.google.com",
        "mail.google.com",
        "drive.google.com",

        # communication
        "slack.com",

        # common cdn's
        "s3.amazonaws.com",
        "clients1.google.com",
        "clients2.google.com",
        "clients3.google.com",
        "clients4.google.com",
        "clients5.google.com",
        "cdn.optimizely.com",

        # link shorteners
        "tc.o",
        "www.bit.ly",
        "bit.ly",
        "ow.ly",
        "j.mp",
        "goo.gl",
        "tinyurl.com",

        # connectivity checking
        "msftncsi.com",
        "www.msftncsi.com",

        # game services
        "v10.events.data.microsoft.com",
        "v20.events.data.microsoft.com",
        "ea.com",

        # misc
        "res.cloudinary.com", #(Used by Facebook for image uploads)
        "gravatar.com",
        "rover.ebay.com",
        "imgs.xkcd.com",
        "netflix.com",
        "alluremedia.com.au", # (Used by Gizmodo sites)
        "tomshardware.com",
        "ocsp.apple.com", # (Used by Apple devices for certificate validation)
        "s.shopify.com",
        "keystone.mwbsys.com", # (Malwarebytes server)
        "dl.dropbox.com",
        "api.ipify.org",
    ]

    # remote list of domains to whitelist
    upstreams = [
        "https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt",
        #"https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/optional-list.txt",
        #"https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/referral-sites.txt",
    ]
